/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Athena with PDBs A757_RL_x64 03-05-2019 14:32 c7c3c8b5c9048c91ecd985eb5fe2edf91b202c0e"
  #define VERSION_INT   757
#endif

